/*
	script for creating the db schema
*/
DROP TABLE IF EXISTS CS_AKICK;
DROP TABLE IF EXISTS CHANS;
DROP TABLE IF EXISTS BOTS;
DROP TABLE IF EXISTS NS_AUTH;
DROP TABLE IF EXISTS NS_ACCESS;
DROP TABLE IF EXISTS NS_NOTIFY;
DROP TABLE IF EXISTS NICKS;
DROP TABLE IF EXISTS AKILL;
DROP TABLE IF EXISTS OPERS;
DROP TABLE IF EXISTS OP_LIST;

CREATE TABLE 'NICKS'(
   NICK_ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
   NICKNAME VARCHAR(33) NOT NULL,
   PASSWORD VARCHAR(33) NOT NULL,
   MASK VARCHAR(128) NOT NULL,
   REALNAME VARCHAR(256) NULL,
   LAST_SEEN BIGINT NOT NULL,
   REGISTERED BIGINT NOT NULL,
   HIDEMAIL TINYINTNOT NULL,
   MEMOMAX INT NULL,
   URL VARCHAR(128) NULL,
   EMAIL VARCHAR(65) NOT NULL,
   MFORWARD INT NOT NULL,
   NOOP TINYINT NOT NULL,
   NOMEMO TINYINT NOT NULL,
   AUTH_CHAN TINYINT NOT NULL,
   AUTH_NOTIFY TINYINT NOT NULL,
   PROTECT TINYINT NOT NULL,
   MLOCK VARCHAR(33) NULL,
   MNOTIFY TINYINT NOT NULL
);


CREATE TABLE NS_ACCESS (
	ACCESS_ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	NICK_ID INT NOT NULL,
	MASK VARCHAR(256) NOT NULL,
	FOREIGN KEY (NICK_ID) REFERENCES NICKS(NICK_ID)
);

CREATE TABLE NS_NOTIFY (
	NOTIFY_ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	NICK_ID INT NOT NULL,
	NOTIFICATION_NICK_ID INT NOT NULL,
	FOREIGN KEY (NICK_ID) REFERENCES NICKS(NICK_ID),
	FOREIGN KEY (NOTIFICATION_NICK_ID) REFERENCES NICKS(NICK_ID)
);

CREATE TABLE NS_AUTH (
	AUTH_ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	TARGET_TYPE INT NOT NULL,
	TARGET INT NOT NULL,
	SENDER INT NOT NULL,
	RECIPIENT INT NOT NULL,
	TIME DATETIME NOT NULL,
	STATUS INT NOT NULL,
	ACCESS INT NOT NULL,
	FOREIGN KEY (SENDER) REFERENCES NICKS(NICK_ID) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (RECIPIENT) REFERENCES NICKS(NICK_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE BOTS (
	BOT_ID INTEGER PRIMARY KEY AUTOINCREMENT,
	NICKNAME VARCHAR(32) NOT NULL,
	PASSWORD VARCHAR(32) NOT NULL,
	USERNAME VARCHAR(32) NOT NULL,
	REALNAME VARCHAR(32) NOT NULL
);

CREATE TABLE CHANS
(
   CHAN_ID INTEGER PRIMARY KEY AUTOINCREMENT,
   NAME VARCHAR(33) NOT NULL,
   PASSWORD VARCHAR(33) NOT NULL,
   DESCRIPTION VARCHAR(256) NOT NULL,
   TIME_REG BIGINT NOT NULL,
   AOP_ENABLED TINYINT NOT NULL,
   HOP_ENABLED TINYINT NOT NULL,
   SOP_ENABLED TINYINT NOT NULL,
   UOP_ENABLED TINYINT NOT NULL,
   VOP_ENABLED TINYINT NOT NULL,
   BOT INT NULL,
   FOUNDER INT NOT NULL,
   SUCCESSOR INT NULL,
   MLOCK VARCHAR(33) NULL,
   TOPIC VARCHAR(1025) NULL,
   TOPIC_USER VARCHAR(33) NULL,
   TOPIC_TIME BIGINT NULL,
   RESTRICTED TINYINT NOT NULL,
   KEEPTOPIC TINYINT NOT NULL,
   AUTOVOP TINYINT NOT NULL,
   MEMOLEVEL INT NOT NULL,
   LEAVEOPS TINYINT NOT NULL,
   OPWATCH TINYINT NOT NULL,
   URL VARCHAR(64) NULL,
   TOPICLOCK INT NULL,
   FOREIGN KEY (BOT) REFERENCES BOTS(BOT_ID) ON DELETE CASCADE ON UPDATE CASCADE,
   FOREIGN KEY (FOUNDER) REFERENCES NICKS(NICK_ID) ON DELETE CASCADE ON UPDATE CASCADE,
   FOREIGN KEY (SUCCESSOR) REFERENCES NICKS(NICK_ID) ON DELETE CASCADE ON UPDATE CASCADE,
   FOREIGN KEY (MEMOLEVEL) REFERENCES OP_TYPE(OP_TYPE_ID) ON DELETE CASCADE ON UPDATE CASCADE, 
   FOREIGN KEY (TOPICLOCK) REFERENCES OP_TYPE(OP_TYPE_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE CS_AKICK (
	AKICK_ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	CHAN INT NOT NULL NOT NULL,
	MASK VARCHAR(256) NOT NULL,
	ADDED_BY VARCHAR(32) NOT NULL,
	ADDED_BY_ACC INT NOT NULL,
	ADDED_ON BIGINT NOT NULL,
	REASON VARCHAR(512) NULL,
	FOREIGN KEY (CHAN) REFERENCES CHANS(CHAN_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE OP_LIST (
	OP_LIST_ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT NOT NULL,
	TYPE INT NOT NULL,
	NICK INT NOT NULL,
	CHAN INT NOT NULL,
	ADDED_BY VARCHAR(32) NOT NULL,
	ADDED_BY_ACC INT NOT NULL,
	ADDED_ON BIGINT,
	FOREIGN KEY (TYPE) REFERENCES OP_TYPE(OP_TYPE_ID) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (NICK) REFERENCES NICKS(NICK_ID) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (CHAN) REFERENCES CHANS(CHAN_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE AKILL (
	AKILL_ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT NOT NULL,
	HOST VARCHAR(256) NOT NULL,
	EXPIRY BIGINT NULL,
	ADDED_BY VARCHAR(256) NOT NULL,
	REASON VARCHAR(1024)
);

CREATE TABLE OPERS (
	USER_ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT NOT NULL,
	NICKNAME INT NOT NULL,
	CAN_AKILL TINYINT NOT NULL,
	CAN_CHGHOST TINYINT NOT NULL,
	CAN_GLOBAL TINYINT NOT NULL,
	CAN_LOCAL TINYINT NOT NULL,
	CAN_KICK TINYINT NOT NULL,
	CAN_KILL TINYINT NOT NULL,
	CAN_SGLINE TINYINT NOT NULL,
	CAN_SKLINE TINYINT NOT NULL,
	CAN_SQLINE TINYINT NOT NULL,
	CAN_SVSNICK TINYINT NOT NULL,
	CAN_SZLINE TINYINT NOT NULL
);

.quit;